services:
  blue:
    image: ghcr.io/hacuba7777/vps:latest      # 全小寫
    restart: unless-stopped
    container_name: blue
    environment:
      - APP_COLOR=blue
    expose:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:8000/healthz'); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks: [web]

  green:
    image: ghcr.io/hacuba7777/vps:latest      # 全小寫
    restart: unless-stopped
    container_name: green
    environment:
      - APP_COLOR=green
    expose:
      - "8002:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:8000/healthz'); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro   # 用你從 repo 同步過去的檔案
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
