services:
  app:
    image: ghcr.io/hacuba7777/vps:latest      # 全小寫
    restart: unless-stopped
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro   # 用你從 repo 同步過去的檔案
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]
    depends_on:
      app:
        condition: service_healthy

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
