global:
  resolve_timeout: 5m

route:
  receiver: email
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 2h

receivers:
  - name: email
    email_configs:
      - to: 'hacuba7777+am@gmail.com'
        from: 'hacuba7777@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'hacuba7777@gmail.com'
        auth_password: '${GMAIL_APP_PASSWORD}'   # ← 重點：用 env 展開
        require_tls: true
        send_resolved: true
