name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}
  TAG: ${{ github.sha }}
  LATEST: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR (GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
          --build-arg GIT_SHA=${{ github.sha }} \
          --build-arg BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
          --build-arg APP_NAME=${{ github.repository }} \
          -t $IMAGE:$TAG -t $IMAGE:$LATEST .

      - name: Push image
        run: |
          docker push $IMAGE:$TAG
          docker push $IMAGE:$LATEST

  deploy:
    needs: build-and-push
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (get Caddyfile & compose)
        uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Prepare /opt/app on EC2
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /opt/app"

      - name: Copy deploy files   # ⬅️ 多加 docker-compose.monitor.yml
        run: scp docker-compose.yml docker-compose.monitor.yml Caddyfile ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/app/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          GHCR_USER='${{ secrets.GHCR_USER }}' GHCR_TOKEN='${{ secrets.GHCR_TOKEN }}' bash -lc '
              set -e
              cd /opt/app
              docker login ghcr.io -u \"$GHCR_USER\" -p \"$GHCR_TOKEN\" || true
              # ⬅️ 同時啟動 app.yml 與 monitor.yml
              docker-compose -f docker-compose.yml -f docker-compose.monitor.yml pull
              docker-compose -f docker-compose.yml -f docker-compose.monitor.yml up -d
          '
          "

      - name: Health check with retry
        run: |
          for i in {1..20}; do
            if curl -fsS https://app.hacuba.site/healthz >/dev/null; then
              echo "healthy"; exit 0
            fi
            echo "waiting for app... ($i)"; sleep 3
          done
          echo "app not ready in time"; exit 1
